jayambe/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.urls import path
from products import views
app_name = 'products'

urlpatterns = [
    path('collection/',views.proView,name="collection"),
    path('mycontact/',views.mycontact,name='connections'),
    path('about/',views.about,name='about'),
    path('detail/<int:id>',views.detail, name='detail'),
    path('test/',views.test)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from tinymce.models import HTMLField

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = HTMLField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product_images/')

    def __str__(self):
        return self.name
    
class myContact(models.Model):
    serial_no = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=17)
    address = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    order = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class myImages(models.Model):
    image = models.ImageField(upload_to= 'product_myImages/')
    time = models.TimeField(auto_created=True)

class about(models.Model):
    about_description = HTMLField()
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    facebook_link = models.URLField(blank=True, null=True)
    twitter_link = models.URLField(blank=True, null=True)
    linkedin_link = models.URLField(blank=True, null=True)
    instagram_link = models.URLField(blank=True, null=True)
    indiamart_link = models.URLField(blank=True, null=True)
    other_social_links = models.TextField(blank=True, null=True)

products/forms.py
from django import forms
from .models import Product
from .models import myContact
from .models import myImages

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'image']

class myContact(forms.ModelForm):
    class Meta:
        model = myContact 
        fields = ['serial_no','number', 'name', 'address', 'company', 'order']

class myImagesForm(forms.ModelForm):
    class Meta:
        model = myImages
        fields = ['image','time']

products/views.py
from django.shortcuts import render
from django.http import HttpResponse
# from django.views.generic.detail import DetailView
from .models import Product
from .models import myContact as myContact_model
from .models import myImages as myImages_model
from .models import about as about_model
from .forms import ProductForm
from .forms import myContact 
from .forms import myImagesForm
# Create your views here.
def test(req):
    # s = '<h1>This is my file</h1>'
    return render(req, 'img2.html')

def proView(req):
    # model = Product
    # template_name = 'products/product_detail.html'
    # context_object_name = 'product'
    if req.method == "POST":
        form = ProductForm(req.POST, req.FILES)
        if form.is_valid():
         form.save()
    form = ProductForm
    img = Product.objects.all()
    return render(req, 'img2.html', {'img':img, 'form':form})

def mycontact(req):
   if req.method == "POST":
      form = myContact(req.POST, req.FILES)
      if form.is_valid():
        form.save()
   form = myContact
   contacts = myContact_model.objects.all()
   return render(req, 'numCollection.html',{'contacts':contacts,'form':form})

def about(req):
   if req.method == "POST":
      form = myImagesForm(req.POST, req.FILES )
      if form.is_valid():
         form.save()
   form = myImagesForm
   images = myImages_model.objects.all()
   about_data = about_model.objects.all()
   return render(req, 'about.html',{'images':images,'form':form,"about":about_data[0] })

def detail(request,id):
    product = Product.objects.get(id=id)
    return render(request, 'prod_des.html',{'id':id,'product':product})

products/templates/about.html
{% include 'main.html' %}

{% block menu %}


    <div class="" style="margin:30px 15px;   box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.5),  -5px -5px 5px rgba(0, 0, 0, 0.5);border-radius: 10px;" >


        <div class="" style="width:80vw;margin:auto;">
            {{ about.about_description | safe }}
        </div>

      <div style="width: 800px; height: 5 00px; margin:auto;" id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
                     <div class="carousel-inner">

                        {% for ele in images %}

                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <img src='{{ ele.image.url }}' width="700" height="400" class="d-block w-100" alt="..." style="border-radius: 10px;">
                            </div>
                        
                        {% endfor %}
                    
                    </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                        </button>
       </div>
       
       
    
    </div>



{% endblock %}

products/templates/img.html
{% include 'main.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Upload files form hear</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" class="btn btn-danger" value="Upload">
    </form>
    <h1>-----------------------</h1>
    <h2>{{ product.name }}</h2>
    <p>Description: {{ product.description }}</p>
    <p>Price: ${{ product.price }}</p>
    {% for x in img %}
    <img src="{{ x.image.url }}" alt="{{ x.name }}" width="300" height="300">
    {% endfor %}
</body>
</html>

products/templates/img2.html
{% include 'main.html' %}

  {% block menu %}

          <div class="container">
            <div class="row row-cols-3">
                
              {% for x in img %}
              <!-- <h1>Productid {{x.id}}</h1> -->
              <div class="col ">
                 <!-- <h1>hello</h1> -->
                <div class="card blur-border" style="width: 18rem;">
                  <img src="{{ x.image.url }}" class="card-img-top" alt="..." style="width: 15rem;">
                  <div class="card-body">
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                  <a href="{% url 'products:detail' x.id %}" > <button>Show</button> </a>
                </div>
              </div>

              {% endfor %}

            </div>
          </div> 
    {% endblock %}
      

      

 

products/templates/main.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Polyplast</title>
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <style>
      .under{
        border:2px solid black;
        
      }
    </style>
  </head>
  <body>
    {% include 'nav.html' %}
<!-- -------------- -->


    {% block menu %}
    {% endblock %}


     
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

products/templates/nav.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Hello, world!</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    <style>
     
  </style>
  </head>
  <body>

    <nav class="" id="zzz" >
      <h1>Jay ambe polyplast</h1>
    </nav>


    <nav class="navbar navbar-expand-lg" style="background-color: rgb(165, 162, 162); color:rgb(177, 61, 61);">
        <div class=" container-fluid">
         
          <div class="collapse navbar-collapse " id="navbarNavDropdown" style="justify-content: space-between;" >
            <ul class="navbar-nav sp_a_color">
              <li class="nav-item">
                <a class="nav-link active " aria-current="page" href="{% url 'products:collection' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="">Offer</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="">Contact</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:about' %}">About</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'products:connections' %}">Connections</a>
              </li>
            </ul>

            <ul class="navbar-nav sp_a_color" >
               <li  class="nav-item " ><a class="nav-link" target="_blank" href="https://www.instagram.com/l_._devendra_._l/">Facebook</a> </li>
            </ul>

          </div>
        </div>
      </nav>

      

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

products/templates/numCollection.html
    {% include 'main.html' %}

    {% block menu %}
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" class="btn btn-danger" value="Upload"></form>
      </form>

      <table class="table">
        <thead>
          <tr>
            <th colspan="1">#</th>
            <th colspan="2">Name</th>
            <th colspan="2">Number</th>
            <th colspan="3">Address</th>
            <th colspan="2">Company</th>
            <th colspan="2">Order</th>

          </tr>
        </thead>
        <tbody>
          {% for ele in contacts %}
          <tr>
            <td colspan="1">{{ele.serial_no}}</td>
            <td colspan="2">{{ele.name}}</td>
            <td colspan="2">{{ele.number}}</td>
            <td colspan="3">{{ele.address}}</td>
            <td colspan="2">{{ele.company}}</td>
            <td colspan="2">{{ele.order}}</td>
          </tr>
          {% endfor %}
          
        </tbody>
      </table>

      {% endblock %}

  

products/templates/prod_des.html
<!DOCTYPE html>
{% include 'main.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.name }} - Product Detail</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <!-- <header>
        <h1>{{ product.name }}</h1>
    </header> -->
    <div class="product-detail">
        <div class="product-image">
            <img src="{{ product.image.url }}">
        </div>
        <div class="product-info" style="margin-top: 0;">
            <h2 class="product-info-header">{{ product.name }}</h2>
            <p>Price: ${{ product.price }}</p>
            <div>{{ product.description | safe }}</div>
            <!-- Add more product details as needed -->
        </div>
    </div>
    <!-- <a href="">Back to Product List</a> -->
</body>
</html>